---
# tasks file for /etc/ansible/ansible_test/roles/nginx
- import_tasks: install.yml
- import_tasks: service.yml
- import_tasks: configure.yml
- import_tasks: add_user_ssh.yml
- import_tasks: firewall.yml
- import_tasks: reboot.yml